name: my_env
channels:
  - conda-forge
  - defaults
dependencies:
  - arrow-cpp=16.1.0
  - asttokens=2.4.1
  - attrs=23.1.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=4.1.0
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.7.4
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.0
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - expat=2.6.2
  - fonttools=4.51.0
  - freetype=2.12.1
  - gflags=2.2.2
  - glog=0.5.0
  - icc_rt=2022.1.0
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.0.0
  - importlib_metadata=8.0.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - jupyterlab_pygments=0.2.2
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libabseil=20240116.2
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.7.1
  - libdeflate=1.17
  - libevent=2.1.12
  - libffi=3.4.4
  - libgrpc=1.62.2
  - libpng=1.6.39
  - libpq=12.17
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libssh2=1.11.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - littleutils=0.2.4
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpmath=1.3.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - nest-asyncio=1.6.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.3.1
  - orc=2.0.1
  - outdated=0.2.2
  - packaging=24.1
  - pandas=2.2.2
  - pandas-flavor=0.6.0
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=0.5.6
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pingouin=0.5.5
  - pip=24.0
  - platformdirs=4.2.2
  - ply=3.11
  - prompt-toolkit=3.0.47
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pyarrow=16.1.0
  - pybind11-abi=5
  - pygments=2.18.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.12.4
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-tzdata=2023.3
  - pytz=2024.1
  - pywin32=305
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - re2=2022.04.01
  - referencing=0.30.2
  - requests=2.32.3
  - rpds-py=0.10.6
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - setuptools=69.5.1
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.2.1
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.6.2
  - statsmodels=0.14.2
  - tabulate=0.9.0
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tinycss2=1.2.1
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - utf8proc=2.6.1
  - vc=14.2
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - wheel=0.43.0
  - win_inet_pton=1.1.0
  - xarray=2023.6.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.2.13
  - zstd=1.5.5
